package com.brendondias.game.logic;

public enum Ninjas {
    CLASSIC_NARUTO, CLASSIC_SASUKE,CLASSIC_SAKURA, CLASSIC_KAKASHI,
    CLASSIC_SHIKAMARU, CLASSIC_INO, CLASSIC_CHOJI, CLASSIC_ASUMA,
    CLASSIC_LEE, CLASSIC_NEJI, CLASSIC_TENTEN, CLASSIC_GAI,
    CLASSIC_HINATA, CLASSIC_KIBA, CLASSIC_SHINO, CLASSIC_KURENAI,
    CLASSIC_GAARA, CLASSIC_TEMARI, CLASSIC_KANKURO, CLASSIC_BAKI
}
